### ISSUE TITLE
Another broken link, this one in Random module docs

### ISSUE THREAD

**Issue by HappMacDonald** [elm/random#8]
https://package.elm-lang.org/packages/elm/random/1.0.0/Random

Docs for the Random.lazy function

> This is a pretty subtle issue, so I recommend reading more about it [here](https://elm-lang.org/hints/0.19.0/bad-recursion)!

looks like it presently points to https://elm-lang.org/hints/0.19.0/bad-recursion which offers a 404, but new url for target appears to be [here](https://elm-lang.org/0.19.0/bad-recursion) at https://elm-lang.org/0.19.0/bad-recursion .

Also if there's better places to report broken docs links than in the github, just lemme know for future reference and I'll have learnt a new thing, thank you kindly folks. :)

**Comment by evancz** [comment]
Thank you for the report! This is the right place for this sort of thing! :)
